# Generated by Django 5.1.5 on 2025-12-16 19:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.CharField(max_length=254)),
                ('email_type', models.CharField(db_index=True, max_length=50)),
                ('context', models.JSONField(default=dict)),
                ('scheduled_for', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('queued', 'Queued'),
                            ('sending', 'Sending'),
                            ('sent', 'Sent'),
                            ('failed', 'Failed'),
                            ('cancelled', 'Cancelled'),
                            ('skipped', 'Skipped'),
                        ],
                        db_index=True,
                        default='queued',
                        max_length=20,
                    ),
                ),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('batch_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='queued_emails',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Queued Email',
                'verbose_name_plural': 'Queued Emails',
                'db_table': 'email_queue_queued_email',
                'ordering': ['scheduled_for'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='emailq_status_sched_idx')],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('user', 'email_type', 'scheduled_for'), name='emailq_user_type_sched_uniq'
                    )
                ],
            },
        ),
    ]
