# Generated by Django 5.1.5 on 2025-12-18 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_queue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='queuedemail',
            name='emailq_user_type_sched_uniq',
        ),
        migrations.AddConstraint(
            model_name='queuedemail',
            constraint=models.UniqueConstraint(
                fields=('to_email', 'email_type', 'scheduled_for', 'context'), name='emailq_toemail_type_sched_ctx_uniq'
            ),
        ),
    ]
