# Generated by Django 5.1.5 on 2026-01-13 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_queue', '0002_remove_queuedemail_emailq_user_type_sched_uniq_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('landing_url', models.CharField(max_length=500)),
                (
                    'queued_email',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='email_queue.queuedemail'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'verbose_name': 'Email Click',
                'verbose_name_plural': 'Email Clicks',
                'db_table': 'email_queue_email_click',
                'ordering': ['-clicked_at'],
                'indexes': [
                    models.Index(fields=['queued_email', '-clicked_at'], name='emailclick_qe_time_idx'),
                    models.Index(fields=['user', '-clicked_at'], name='emailclick_user_time_idx'),
                ],
            },
        ),
    ]
