# Generated by Django 5.1.5 on 2026-03-06 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_queue", "0003_emailclick"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailUnsubscribe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.CharField(db_index=True, max_length=254)),
                ("category", models.CharField(db_index=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("unsubscribed_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_unsubscribes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Unsubscribe",
                "verbose_name_plural": "Email Unsubscribes",
                "db_table": "email_queue_email_unsubscribe",
                "ordering": ["-unsubscribed_at"],
                "indexes": [models.Index(fields=["category", "-unsubscribed_at"], name="emailunsub_cat_time_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("email", "category"), name="emailunsub_email_category_uniq")
                ],
            },
        ),
    ]
