# Generated by Django 5.1.5 on 2026-03-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_queue", "0004_emailunsubscribe"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailReplyEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message_id", models.CharField(max_length=255, unique=True)),
                ("from_email", models.CharField(blank=True, max_length=254)),
                ("to_email", models.CharField(blank=True, max_length=254)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("token_email", models.CharField(blank=True, max_length=254)),
                ("token_email_type", models.CharField(blank=True, db_index=True, max_length=50)),
                ("token_category", models.CharField(blank=True, db_index=True, max_length=50)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ignored_auto_reply", "Ignored Auto Reply"),
                            ("ignored_not_enabled", "Ignored Not Enabled"),
                            ("category_stop", "Category Stop"),
                            ("email_type_stop", "Email Type Stop"),
                            ("duplicate", "Duplicate"),
                        ],
                        max_length=32,
                    ),
                ),
                ("cancelled_count", models.IntegerField(default=0)),
                ("processed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("raw_payload", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Email Reply Event",
                "verbose_name_plural": "Email Reply Events",
                "db_table": "email_queue_email_reply_event",
                "ordering": ["-processed_at"],
                "indexes": [models.Index(fields=["action", "-processed_at"], name="emailreply_action_time_idx")],
            },
        ),
    ]
